{% set name = "dftd4-python" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/releases/download/v{{ version }}/dftd4-{{ version }}-source.tar.xz
  sha256: d3781763390c349794d70663e4e54e368d19a5869c98fe939b32e9069432201b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('c') }}    # [unix]
    - {{ stdlib('m2w64_c') }}    # [win]
    - cffi                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - meson-python                        # [build_platform != target_platform]
    - pkg-config
    - python                              # [build_platform != target_platform]
    - python-build                        # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
  host:
    - cffi
    - dftd4 >={{ version }}
    - libblas
    - liblapack
    - meson-python
    - pip
    - python
    - python-build
    - setuptools
  run:
    - cffi
    - numpy
    - python

test:
  imports:
    - dftd4
  requires:
    - pytest
    - setuptools  # needs pkg_resources
    - qcelemental
    - ase
  commands:
    - pytest --pyargs dftd4 -vv

about:
  home: https://github.com/dftd4/dftd4/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D4 project
  description: |
    Python interface for the generally applicable atomic-charge dependent
    London dispersion correction.
  doc_url: https://dftd4.readthedocs.io

extra:
  recipe-maintainers:
    - awvwgk
    - marvinfriede
