{% set name = "dftd4-python" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/archive/v{{ version }}.tar.gz
  sha256: 69830a32be61e683f3246239bdbf6a5ab8a0c902c76716f215262d16082a9e6d

build:
  number: 0
  skip: true  # [osx and py<38]
  skip: true  # [(not x86_64 and linux) and (python_impl != 'cpython')]
  script:
    - set -ex  # [unix]
    - cd python
    - >
      meson setup _build ${MESON_ARGS__###conda-selector###__unix:---prefix=${PREFIX} --libdir=lib}   --prefix=%PREFIX% --pkg-config-path=%LIBRARY_PREFIX%\lib\pkgconfig;%PREFIX%\lib\pkgconfig  # [win] -Dpython_version={{ PYTHON }} --buildtype=release
    - meson compile -C _build
    - meson install -C _build --no-rebuild
    - copy %SRC_DIR%\assets\parameters.toml %PREFIX%\lib\site-packages\dftd4  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - meson
    - ninja
    - python
    - pkg-config
  host:
    - python
    - cffi
    - pip
    - dftd4 >={{ version }}
    - libblas
    - liblapack
  run:
    - python
    - cffi
    - numpy


test:
  imports:
    - dftd4
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
  commands:
    - pytest --pyargs dftd4 -vv  # [build_platform == target_platform]

about:
  home: https://github.com/dftd4/dftd4/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D4 project
  description: |
    Python interface for the generally applicable atomic-charge dependent
    London dispersion correction.

extra:
  recipe-maintainers:
    - awvwgk
