{% set name = "dftd4-python" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/archive/v{{ version }}.tar.gz
  sha256: 60d4f30d97cae95a7b48a99e10848ef600b605f9da98c4893a6034bded1a7f24
  patches:
    - disable-ffibuilder.patch

build:
  number: 0
  skip: true  # [win or (osx and (python_impl == 'cpython' and py<38))]

requirements:
  build:
    - {{ compiler('c') }}
    - meson 0.53.*
    - ninja
    - python
    - cffi
    - pkg-config
  host:
    - python
    - pip
    - dftd4
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - python
    - cffi
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('dftd4', max_pin='x.x') }}


test:
  imports:
    - dftd4
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
  commands:
    - pytest --pyargs dftd4 -vv

about:
  home: https://github.com/dftd4/dftd4/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D4 project
  description: |
    Python interface for the generally applicable atomic-charge dependent
    London dispersion correction.

extra:
  recipe-maintainers:
    - awvwgk
