{% set name = "dftd4-python" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/releases/download/v{{ version }}/dftd4-{{ version }}-source.tar.xz
  sha256: 56b3b4650853a34347d3d56c93d7596ecbe2208c4a14dbd027959fd4a009679d

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - cffi                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - meson                               # [build_platform != target_platform]
    - pkg-config                          # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cffi
    - dftd4 >={{ version }}
    - libblas
    - liblapack
    - meson
    - pkg-config
    - pip
    - python
  run:
    - cffi
    - numpy
    - python

test:
  imports:
    - dftd4
  requires:
    - pytest
    - setuptools  # needs pkg_resources
    - qcelemental
    - ase
  commands:
    - pytest --pyargs dftd4 -vv

about:
  home: https://github.com/dftd4/dftd4/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D4 project
  description: |
    Python interface for the generally applicable atomic-charge dependent
    London dispersion correction.
  doc_url: https://dftd4.readthedocs.io

extra:
  recipe-maintainers:
    - awvwgk
