{% set name = "dftd4-python" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd4/dftd4/archive/v{{ version }}.tar.gz
  sha256: 60d4f30d97cae95a7b48a99e10848ef600b605f9da98c4893a6034bded1a7f24
  patches:
    - python-version.patch

build:
  number: 1
  skip: true  # [osx and py<38]
  #skip: true  # [(not x86_64 and linux) and (python_impl == 'cpython' and py==39)]
  script:
    - set -ex  # [unix]
    - cd python
    - meson setup _build ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib} --buildtype=release -Dpython_version=$PYTHON  # [unix]
    - meson setup _build --prefix=%PREFIX% --buildtype=release --pkg-config-path=%PREFIX%\lib\pkgconfig -Dpython_version=%PYTHON%  # [win]
    - meson compile -C _build
    - meson install -C _build --no-rebuild
    - copy %SRC_DIR%\assets\parameters.toml %PREFIX%\lib\site-packages\dftd4  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - meson
    - ninja
    - python
    - pkg-config
  host:
    - python
    - cffi
    - pip
    - dftd4 >={{ version }}
    - libblas
    - liblapack
  run:
    - python
    - cffi
    - numpy
    - {{ pin_compatible('dftd4', max_pin='x.x') }}


test:
  imports:
    - dftd4
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
  commands:
    - pytest --pyargs dftd4 -vv  # [build_platform == target_platform]

about:
  home: https://github.com/dftd4/dftd4/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D4 project
  description: |
    Python interface for the generally applicable atomic-charge dependent
    London dispersion correction.

extra:
  recipe-maintainers:
    - awvwgk
